baseURL = 'https://migeel.sk/'
languageCode = 'en-us'
title = "Michal's low level corner"
theme = 'hugo-theme-stack'

[permalinks.page]
post = '/blog/:year/:month/:day/:slug/'
page = ':slug'

[[params.widgets.page]]
type = "archives"

[params.widgets.page.params]
limit = 5

[[params.widgets.page]]
type = "tag-cloud"

[params.widgets.page.params]
limit = 10

[[params.widgets.homepage]]
type = "archives"

[params.widgets.homepage.params]
limit = 5

[[params.widgets.homepage]]
type = "tag-cloud"

[params.widgets.homepage.params]
limit = 10

[params.footer]
since = 2001

[params.imageProcessing.content]
enabled = false

#[params.sidebar.avatar]
#enabled = false

[params.sidebar]
subtitle = "Things about C#, .NET and low level topics I find interesting"


[[menu.social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/MichalStrehovsky"

[menu.social.params]
icon = "brand-github"

[[menu.social]]
identifier = "twitter"
name = "Twitter"
url = "https://twitter.com/MStrehovsky"

[menu.social.params]
icon = "brand-twitter"

[[menu.social]]
identifier = "rss"
name = "RSS"
url = "/index.xml"

[menu.social.params]
icon = "rss"

[markup.highlight]
noClasses = false
#lineNos = true
#lineNumbersInTable = true
